### ISSUE TITLE
Select yanked scripts

### ISSUE THREAD

**Issue by ikeasamoahansah** [ikeasamoahansah/clipboard.nvim#1]
Currently, you can only view yanked scripts, make it so that you can select them as well

**Comment by JohananOppongAmoateng** [comment]
@ikeasamoahansah assign to me

**Comment by ikeasamoahansah** [comment]
@JohananOppongAmoateng you can go ahead and submit a PR

**Comment by Aliqyan-21** [comment]
@ikeasamoahansah can I work on it if the issue is still open?

**Comment by JohananOppongAmoateng** [comment]
@Aliqyan-21 I am working on it will push the code today

**Comment by ikeasamoahansah** [comment]
#2 closed this
